version: "3.8"

services:
  python-base:
    image: python-base:${PY_VERSION}
    build:
      context: .
      target: python-base
      args:
        - PY_VERSION=${PY_VERSION}
        - POETRY_VERSION=${POETRY_VERSION}
    command: sleep infinity

  builder-base:
    image: builder-base:${PY_VERSION}
    build:
      context: .
      target: builder-base
    command: sleep infinity

  python-dev:
    image: python-dev:${PY_VERSION}
    build:
      context: .
      target: development
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env

  python-prod:
    image: python-prod:${PY_VERSION}
    build:
      context: .
      target: production
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
